# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MaiChain
email: lucas@yunlin.io
keywords: >- # this means to ignore newlines until "baseurl:"
  Blockchain, Dapp Development, Bitcoin, Ethereum, EOS
description: >- # this means to ignore newlines until "baseurl:"
  Blockchain Industry Application Solutions.
  Focusing on the underlying technology of block.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Team names, titles and social links
people:
- name: Lucas Zhang
  pic: 1.png
  titles:
    - MaiChain CEO
    - Senior Fullstack Engineer
    - Former Architect at MaiCoin

- name: David Zhang
  pic: 2.jpg
  titles:
    - MaiChain Co-Founder
    - Senior Fullstack Engineer
    - Open Source Enthusiast

- name: Levi Chen
  pic: 3.png
  titles:
    - MaiChain Co-Founder
    - Senior Fullstack Engineer
    - Open Source Enthusiast

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: '#'
  - title: facebook
    url: '#'
  - title: github
    url: '#'

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
